version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./:/app
      -  $HOME/.aws/credentials:/home/user/.aws/credentials:ro
    command: >
      sh -c "python3 main.py"
