version: "3.8"

services:
  app:
#    environment:
#      - profile=${PROFILE}
    build:
      context: .
    volumes:
      - ./:/app
      -  $HOME/.aws/credentials:/home/user/.aws/credentials:ro
    command: >
      sh -c "python3 main.py"
